CREATE TABLE exchange_codes(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) UNIQUE
);
ALTER TABLE exchange_codes
    ADD PRIMARY KEY(id);


CREATE TABLE exchange_history(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    code_id INT,
    dateTime TIMESTAMP,
    open DECIMAL,
    high DECIMAL,
    low DECIMAL,
    close DECIMAL,
    volume DECIMAL
);
ALTER TABLE exchange_history
    ADD PRIMARY KEY(id);
ALTER TABLE exchange_history
    ADD FOREIGN KEY(code_id) REFERENCES exchange_codes(id);
