-- Zadanie 1
SELECT LAST_NAME || ' - ' || SALARY AS WYNAGRODZENIE
FROM EMPLOYEES
WHERE (DEPARTMENT_ID IN (20, 50)) AND (SALARY BETWEEN 2000 AND 7000)
ORDER BY LAST_NAME
-- Zadanie 2
SELECT HIRE_DATE, LAST_NAME, :user_column
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2005
ORDER BY :user_column;
-- Zadanie 3
SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME, SALARY, PHONE_NUMBER
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, 3, 1) = 'e'AND FIRST_NAME LIKE '%' || :user_firstname_part || '%'
ORDER BY 1 DESC, 2;
-- Zadanie 4
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
    ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS MIESIACE_PRZEPRACOWANE,
    CASE
        WHEN ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) <= 150 THEN SALARY * 0.10
        WHEN ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) <= 200 THEN SALARY * 0.20
        ELSE SALARY * 0.30
    END AS WYSOKOSC_DODATKU
FROM EMPLOYEES
ORDER BY MIESIACE_PRZEPRACOWANE;
-- Zadanie 5
SELECT D.DEPARTMENT_ID, SUM(E.SALARY) AS SUMA_ZAROBKOW, ROUND(AVG(E.SALARY)) AS SREDNIA_ZAROBKOW
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = D.DEPARTMENT_ID) > 5000
GROUP BY D.DEPARTMENT_ID;
-- Zadanie 6
SELECT E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.JOB_ID
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Toronto';
-- Zadanie 7
SELECT A.FIRST_NAME || ' ' || A.LAST_NAME AS JENNIFER,
       B.FIRST_NAME || ' ' || B.LAST_NAME AS WSPÓŁPRACOWNIK
FROM EMPLOYEES A
JOIN EMPLOYEES B ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE A.FIRST_NAME = 'Jennifer'
  AND A.EMPLOYEE_ID != B.EMPLOYEE_ID;
-- Zadanie 8
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID IS NULL;
-- Zadanie 9
-- CREATE TABLE JOB_GRADES AS (SELECT * FROM HR.JOB_GRADES);
-- Zadanie 10
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME, E.JOB_ID, D.DEPARTMENT_NAME, E.SALARY,
       (SELECT G.GRADE FROM JOB_GRADES G WHERE E.SALARY BETWEEN G.MIN_SALARY AND G.MAX_SALARY)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
-- Zadanie 11
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME, E.SALARY
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY E.SALARY DESC;
-- Zadanie 12
SELECT E.EMPLOYEE_ID, E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME LIKE '%u%'
);

